### PR TITLE
Updated content from codeRIT to BrickHack

### LINKED ISSUE #54: Replace content with BrickHack club info
Now that our club has transitioned to being BrickHack instead of codeRIT, we need to update our site content. Specifically:
- [ ] Update club name
- [ ] Update domain to `club.brickhack.io` (low priority, can be moved to a separate issue)
- [ ] Update content to describe BrickHack better based on the info provided in its constitution
- [ ] Add "more info coming soon!" and "discord server coming soon!" blurbs

### PR DESCRIPTION
**Pull request by skyegallup**
- Updated club name, images, links, etc.
- Replaced body content to better reflect our club's goals
- Temporarily commented out Facebook group link and disabled "join our Discord" button

Fixes #54

### CODE REVIEW

**Comment by peterkos** [comment]
I think we should add a little blurb above "more info coming soon" that highlights that BrickHack is our main event just to make the distinction clear for now!

**Review by peterkos — APPROVED** [review]
LGTM! see comment before this review

**Comment by clairegallup** [comment]
@peterkos Does this work?
image

**Comment by peterkos** [comment]
@clairegallup I think we should add a link to `BrickHack` there as it's most likely people will click that to go to the site vs. scroll down more. I don't personally see the harm in putting the link again there (while also keeping it in the Events section below), thoughts?

**Comment by clairegallup** [comment]
That makes sense. I'll do that and push my changes for a final review.

**Comment by clairegallup** [comment]
Does this work? 
image

**Pull request merged**
